# Generated by Django 5.1.3 on 2024-11-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('IdUser', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NameUser', models.CharField(max_length=50)),
                ('CorreoUse', models.CharField(max_length=30)),
            ],
        ),
    ]
