# Generated by Django 5.1.3 on 2024-11-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('IdPlaga', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NamePlaga', models.CharField(max_length=100)),
                ('DescPlaga', models.TextField()),
                ('FotoPlaga', models.ImageField(blank=True, null=True, upload_to='plagas/')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='PassUser',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefonoUser',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='CorreoUse',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='IdUser',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registro',
            name='NameUser',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojita.registro')),
                ('Plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojita.plaga')),
            ],
        ),
    ]
